import { useEffect } from "react";
import { useAsync } from "react-use";

import { pdfRenderService } from "@/features/pdf/pdfRenderService";

import { useClientSearchContext } from "../clientSearch/clientSearchContext";
import { PDFProps } from "./PDF";

export const useRenderPDF = ({
  cardSelectionMode,
  pageSize,
  pageWidth,
  pageHeight,
  bleedEdgeMM,
  roundCorners,
  drawCardCutLines,
  drawPageCutLines,
  cutLineLengthMM,
  cutLineOffsetMM,
  cutLineThicknessMM,
  cutLineColor,
  cutLinePlacement,
  cutLineShape,
  cardSpacingRowMM,
  cardSpacingColMM,
  pageMarginTopMM,
  pageMarginBottomMM,
  pageMarginLeftMM,
  pageMarginRightMM,
  cardDocumentsByIdentifier,
  projectMembers,
  projectCardback,
  imageQuality,
  imageDPI,
  jpgQuality,
  scmMode,
  scmPaperSize,
  scmVariant,
  scmRegistration,
  scmDuplex,
  scmOffsetXPx,
  scmOffsetYPx,
  scmOffsetAngleDeg,
}: Omit<PDFProps, "fileHandles">) => {
  const { clientSearchService } = useClientSearchContext();
  const {
    value: url,
    loading,
    error,
  } = useAsync(async () => {
    const fileHandles = await clientSearchService.getFileHandlesByIdentifier(
      cardDocumentsByIdentifier
    );
    return pdfRenderService.renderPDFInWorker({
      cardSelectionMode,
      pageSize,
      pageWidth,
      pageHeight,
      bleedEdgeMM,
      roundCorners,
      drawCardCutLines,
      drawPageCutLines,
      cutLineLengthMM,
      cutLineOffsetMM,
      cutLineThicknessMM,
      cutLineColor,
      cutLinePlacement,
      cutLineShape,
      cardSpacingRowMM,
      cardSpacingColMM,
      pageMarginTopMM,
      pageMarginBottomMM,
      pageMarginLeftMM,
      pageMarginRightMM,
      cardDocumentsByIdentifier,
      projectMembers,
      projectCardback,
      imageQuality,
      imageDPI,
      jpgQuality,
      scmMode,
      scmPaperSize,
      scmVariant,
      scmRegistration,
      scmDuplex,
      scmOffsetXPx,
      scmOffsetYPx,
      scmOffsetAngleDeg,
      fileHandles,
    });
  }, [
    cardSelectionMode,
    pageSize,
    pageWidth,
    pageHeight,
    bleedEdgeMM,
    roundCorners,
    drawCardCutLines,
    drawPageCutLines,
    cutLineLengthMM,
    cutLineThicknessMM,
    cutLineColor,
    cutLinePlacement,
    cutLineShape,
    cardSpacingRowMM,
    cardSpacingColMM,
    pageMarginTopMM,
    pageMarginBottomMM,
    pageMarginLeftMM,
    pageMarginRightMM,
    cardDocumentsByIdentifier,
    projectMembers,
    projectCardback,
    imageQuality,
    imageDPI,
    jpgQuality,
    scmMode,
    scmPaperSize,
    scmVariant,
    scmRegistration,
    scmDuplex,
    scmOffsetXPx,
    scmOffsetYPx,
    scmOffsetAngleDeg,
  ]);

  useEffect(() => (url ? () => URL.revokeObjectURL(url) : undefined), [url]);
  return { url, loading, error };
};
