FROM ubuntu:20.04

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install additional dependencies
RUN set -eux; \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip \
        python3-dev \
        gcc \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements.txt
COPY requirements.txt /MPCAutofill/
WORKDIR /MPCAutofill

# Install pip requirements
RUN pip3 install gunicorn wheel
RUN pip3 install -r requirements.txt

# Copy repository
COPY . /MPCAutofill

# Create a non-root user and add permission to access the /MPCAutofill folder
RUN adduser -u 5678 --disabled-password --gecos "" mpcautofill && \
    chown -R mpcautofill /MPCAutofill
USER mpcautofill

# Prepare folder for static files
RUN mkdir -p static

# Configure MPCAutofill settings
RUN echo "DJANGO_SECRET_KEY=$(openssl rand -base64 12)" >> MPCAutofill/MPCAutofill/.env
RUN echo "DJANGO_DEBUG=True" >> MPCAutofill/MPCAutofill/.env
# Update Elasticsearch hostname
RUN sed -i "s/localhost:9200/elasticsearch:9200/g" MPCAutofill/MPCAutofill/settings.py

# Prepare start
WORKDIR /MPCAutofill/MPCAutofill
RUN chmod +x /MPCAutofill/docker/entrypoint.sh

ENTRYPOINT ["/MPCAutofill/docker/entrypoint.sh"]

EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "MPCAutofill.wsgi"]
