# Generated by Django 3.2.4 on 2021-08-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="synopsis",
            field=models.TextField(max_length=140),
        ),
    ]
