# Generated by Django 3.2.4 on 2021-08-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_synopsis"),
    ]

    operations = [
        migrations.AddField(
            model_name="showcaseblogpost",
            name="card_ids",
            field=models.CharField(blank=True, default="", max_length=800),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="showcaseblogpost",
            name="cards",
            field=models.ManyToManyField(blank=True, to="cardpicker.Card"),
        ),
        # migrations.RemoveField(
        #     model_name='showcaseblogpost',
        #     name='cards',
        # )
    ]
