# Generated by Django 4.2.3 on 2023-08-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_showcaseblogpost_card_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="showcaseblogpost",
            name="cards",
        ),
    ]
