name = "image-cdn"
main = "src/index.ts"
compatibility_date = "2026-06-13"
workers_dev = true

[vars]
GOOGLE_CLIENT_ID = ""

[secrets]
required = [ "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN" ]

[[r2_buckets]]
binding = "thumbnails"
bucket_name = "thumbnails"

[[workflows]]
name = "thumbnail-refresh"
binding = "THUMBNAIL_REFRESH_WORKFLOW"
class_name = "ThumbnailRefreshWorkflow"
schedules = ["0 0 * * *"]

[observability]
enabled = true

[[ratelimits]]
name = "GOOGLE_DRIVE_RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 12000, period = 10 }
