import os
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import attr
import enlighten
import InquirerPy
from fpdf import FPDF

from src.constants import THREADS, States
from src.exc import ImageDownloadError
from src.formatting import bold
from src.logging import logger
from src.order import CardOrder
from src.processing import (
    DTC_CARD_HEIGHT_INCHES,
    DTC_CARD_WIDTH_INCHES,
    ImagePostProcessingConfig,
    calculate_dtc_target_pixel_size,
    post_process_image,
    save_processed_image,
)


@dataclass
class PdfXConversionConfig:
    icc_profile_path: Optional[str] = None
    ghostscript_path: Optional[str] = None


def get_export_directory(order_name: Optional[str]) -> str:
    basename = os.path.basename(str(order_name)) or "cards.xml"
    return os.path.join("export", os.path.splitext(basename)[0])


def get_ghostscript_path(explicit_path: Optional[str] = None) -> Optional[str]:
    if explicit_path:
        return explicit_path
    for candidate in ["gs", "gswin64c", "gswin32c"]:
        if resolved := shutil.which(candidate):
            return resolved
    if sys.platform == "win32":
        installs = list(Path(os.environ.get("ProgramFiles", r"C:\Program Files")).glob("gs/gs*/bin/gswin*c.exe"))
        if installs:
            return str(max(installs, key=os.path.getmtime))
    elif sys.platform == "darwin" and os.path.isfile("/usr/local/bin/gs"):
        return "/usr/local/bin/gs"
    return None


def get_ghostscript_version(gs_path: str) -> Optional[str]:
    try:
        result = subprocess.run([gs_path, "-version"], capture_output=True, text=True, check=False)
    except Exception:
        return None
    version = result.stdout.strip().splitlines()
    return version[0] if version else None


def _postscript_string(value: str) -> str:
    return "(" + value.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)") + ")"


def _generate_pdfx_definition(title: str, icc_profile_path: Optional[str]) -> str:
    """
    Generate the PDF/X-1a definition PostScript (based on Ghostscript's lib/PDFX_def.ps) which
    supplies the metadata and output intent that the PDF/X-1a standard requires. The output is
    tagged for the US Web Coated (SWOP) printing condition which DriveThruCards expects; when an
    ICC profile is available it is embedded as the output intent's destination profile.
    """
    lines = [
        "%!",
        "% PDF/X-1a definition file generated by the MPC Autofill desktop tool.",
        "[ /GTS_PDFXVersion (PDF/X-1:2001)",
        "  /GTS_PDFXConformance (PDF/X-1a:2001)",
        f"  /Title {_postscript_string(title)}",
        "  /Trapped /False",
        "  /DOCINFO pdfmark",
        "[/_objdef {OutputIntent_PDFX} /type /dict /OBJ pdfmark",
        "[{OutputIntent_PDFX} <<",
        "  /Type /OutputIntent",
        "  /S /GTS_PDFX",
        "  /OutputCondition (US Web Coated \\(SWOP\\))",
        "  /Info (U.S. Web Coated \\(SWOP\\) v2)",
        "  /OutputConditionIdentifier (CGATS TR 001)",
        "  /RegistryName (http://www.color.org)",
        ">> /PUT pdfmark",
    ]
    if icc_profile_path:
        posix_icc_path = Path(icc_profile_path).as_posix()
        lines[2:2] = [f"/ICCProfile {_postscript_string(posix_icc_path)} def"]
        lines += [
            "[/_objdef {icc_PDFX} /type /stream /OBJ pdfmark",
            "[{icc_PDFX} << /N 4 >> /PUT pdfmark",
            "[{icc_PDFX} ICCProfile (r) file /PUT pdfmark",
            "[{OutputIntent_PDFX} << /DestOutputProfile {icc_PDFX} >> /PUT pdfmark",
        ]
    lines += ["[{Catalog} << /OutputIntents [ {OutputIntent_PDFX} ] >> /PUT pdfmark", ""]
    return "\n".join(lines)


def verify_pdfx_output(output_path: str) -> bool:
    """
    Lightweight preflight of the converted file: Ghostscript writes the document info dictionary
    and output intent uncompressed, so their absence proves the file is not the PDF/X-1a we asked
    for (a zero exit code from Ghostscript alone does not).
    """
    with open(output_path, "rb") as f:
        contents = f.read()
    return b"(PDF/X-1a:2001)" in contents and b"/OutputIntents" in contents


def convert_pdf_to_pdfx(
    source_path: str,
    output_path: str,
    config: PdfXConversionConfig,
) -> bool:
    gs_path = get_ghostscript_path(config.ghostscript_path)
    if not gs_path:
        logger.warning("Ghostscript was not found. Skipping PDF/X-1a conversion.")
        return False

    output_directory = os.path.dirname(output_path) or "."
    os.makedirs(output_directory, exist_ok=True)
    fd, temporary_output_path = tempfile.mkstemp(
        dir=output_directory,
        prefix=f".{os.path.splitext(os.path.basename(output_path))[0]}-",
        suffix=".pdf",
    )
    os.close(fd)

    with tempfile.NamedTemporaryFile("w", suffix=".ps", delete=False) as pdfx_definition_file:
        pdfx_definition_file.write(
            _generate_pdfx_definition(
                title=os.path.splitext(os.path.basename(output_path))[0], icc_profile_path=config.icc_profile_path
            )
        )
        pdfx_definition_path = pdfx_definition_file.name

    cmd = [
        gs_path,
        "-dBATCH",
        "-dNOPAUSE",
        "-dNOSAFER",  # Allow file system access for ICC profile and output
        "-sDEVICE=pdfwrite",
        "-dCompatibilityLevel=1.3",
        "-dPDFX=1",  # PDF/X-1; conformance level PDF/X-1a:2001 is declared in the definition file
        "-dDownsampleColorImages=false",
        "-dDownsampleGrayImages=false",
        "-dDownsampleMonoImages=false",
        "-sProcessColorModel=DeviceCMYK",
        "-sColorConversionStrategy=CMYK",
        f"-sOutputFile={temporary_output_path}",
    ]
    if config.icc_profile_path:
        cmd.append(f"-sOutputICCProfile={config.icc_profile_path}")
    cmd += [pdfx_definition_path, source_path]

    logger.debug(f"Ghostscript command: {' '.join(cmd)}")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            logger.warning(
                "Ghostscript failed to convert PDF/X-1a.\n" f"stdout: {result.stdout}\n" f"stderr: {result.stderr}"
            )
            return False
        if not verify_pdfx_output(temporary_output_path):
            logger.warning(
                "Ghostscript exited successfully but the output failed PDF/X-1a verification "
                "(missing PDF/X-1a version marker or output intent)."
            )
            return False
        os.replace(temporary_output_path, output_path)
        return True
    finally:
        os.unlink(pdfx_definition_path)
        if os.path.exists(temporary_output_path):
            os.unlink(temporary_output_path)


@attr.s
class PdfExporter:
    order: CardOrder = attr.ib()
    state: str = attr.ib(init=False, default=States.initialising)
    pdf: FPDF = attr.ib(default=None)
    card_width_in_inches: float = attr.ib(default=2.73)
    card_height_in_inches: float = attr.ib(default=3.71)
    file_num: int = attr.ib(default=1)
    number_of_cards_per_file: int = attr.ib(default=60)
    paths_by_slot: dict[int, tuple[str, str]] = attr.ib(default={})
    save_path: str = attr.ib(default="")
    separate_faces: bool = attr.ib(default=False)
    current_face: str = attr.ib(default="all")
    export_mode: str = attr.ib(default="standard")
    pdfx_config: Optional[PdfXConversionConfig] = attr.ib(default=None)
    image_post_processing_config: Optional[ImagePostProcessingConfig] = attr.ib(default=None)
    manager: enlighten.Manager = attr.ib(init=False, default=attr.Factory(enlighten.get_manager))
    status_bar: enlighten.StatusBar = attr.ib(init=False, default=False)
    download_bar: enlighten.Counter = attr.ib(init=False, default=None)
    processed_bar: enlighten.Counter = attr.ib(init=False, default=None)
    saved_files: list[str] = attr.ib(init=False, factory=list)
    processed_image_paths: dict[str, str] = attr.ib(init=False, factory=dict)

    def configure_bars(self) -> None:
        num_images = len(self.order.fronts.cards_by_id) + len(self.order.backs.cards_by_id)
        num_cards = len(self.order.fronts.slots())
        status_format = "State: {state}"
        self.status_bar = self.manager.status_bar(
            status_format=status_format,
            state=f"{bold(self.state)}",
            position=1,
            leave=False,  # transient - cleared when the export finishes, unlike the counters below
        )
        # all bars are transient (leave=False): they're live UI while the export runs and are
        # cleared when it ends - the log output is the permanent record
        self.download_bar = self.manager.counter(total=num_images, desc="Images Downloaded", position=2, leave=False)
        self.processed_bar = self.manager.counter(total=num_cards, desc="Cards Added to PDF", position=3, leave=False)

        self.download_bar.refresh()
        self.processed_bar.refresh()

    def set_state(self, state: str) -> None:
        self.state = state
        self.status_bar.update(state=f"{bold(self.state)}")
        self.status_bar.refresh()

    def __attrs_post_init__(self) -> None:
        if self.export_mode == "drive_thru_cards":
            # DriveThruCards Premium Euro Poker requires 2.73" x 3.71" with bleed
            self.card_width_in_inches = DTC_CARD_WIDTH_INCHES
            self.card_height_in_inches = DTC_CARD_HEIGHT_INCHES
            self.separate_faces = False
            # Build one combined PDF per order using the actual exported slots.
            # This is more robust than trusting `details.quantity`, which can
            # under-report cards in some XMLs that still enumerate valid slots.
            self.number_of_cards_per_file = max(1, len(self.order.fronts.slots()))
        else:
            self.ask_questions()
        self.configure_bars()
        self.generate_file_path()

    def ask_questions(self) -> None:
        questions = [
            {
                "type": "list",
                "name": "split_faces",
                "message": "Do you want the front and back of the cards in separate PDFs? (required for MPC).",
                "default": 0,
                "choices": [
                    InquirerPy.base.control.Choice(False, name="No"),
                    InquirerPy.base.control.Choice(True, name="Yes"),
                ],
            },
            {
                "type": "number",
                "name": "cards_per_file",
                "message": "How many cards should be included in the generated files? Note: The more cards per file, "
                + "the longer the processing will take and the larger the file size will be.",
                "default": 60,
                "when": lambda result: result["split_faces"] is False,
                "transformer": lambda result: 1 if (int_result := int(result)) < 1 else int_result,
            },
        ]
        answers = InquirerPy.prompt(questions)
        if answers["split_faces"]:
            self.separate_faces = True
            self.number_of_cards_per_file = 1
        else:
            self.number_of_cards_per_file = (
                1 if (int_cards_per_file := int(answers["cards_per_file"])) < 1 else int_cards_per_file
            )

    def generate_file_path(self) -> None:
        self.save_path = get_export_directory(self.order.name) + "/"
        os.makedirs(self.save_path, exist_ok=True)
        if self.separate_faces:
            for face in ["backs", "fronts"]:
                os.makedirs(self.save_path + face, exist_ok=True)

    def generate_pdf(self) -> None:
        pdf = FPDF("P", "in", (self.card_width_in_inches, self.card_height_in_inches))
        self.pdf = pdf

    def add_image(self, image_path: str) -> None:
        self.pdf.add_page()
        if self.export_mode == "drive_thru_cards" and self.image_post_processing_config:
            tmp_path = self.processed_image_paths.get(image_path)
            if tmp_path is None:
                with open(image_path, "rb") as f:
                    raw_image = f.read()
                # post_process_image handles resizing to target_pixel_size (set in execute())
                # which ensures the correct DPI for the DTC card dimensions
                processed_image, icc_profile_bytes = post_process_image(
                    raw_image=raw_image, config=self.image_post_processing_config
                )
                # Save to a temporary file so fpdf embeds the JPEG data directly
                # (passing BytesIO causes fpdf to re-encode with FlateDecode, bloating file size).
                # Cached per source path so a repeated card (e.g. the shared cardback) is processed
                # once and fpdf's per-path image cache embeds its data once per PDF. Temp files are
                # cleaned up at the end of execute().
                ext = ".jpg" if self.image_post_processing_config.output_format == "JPEG" else ".png"
                with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
                    tmp_path = tmp.name
                self.processed_image_paths[image_path] = tmp_path
                save_processed_image(
                    processed_image,
                    file_path=tmp_path,
                    config=self.image_post_processing_config,
                    icc_profile_bytes=icc_profile_bytes,
                )
            self.pdf.image(
                tmp_path,
                x=0,
                y=0,
                w=self.card_width_in_inches,
                h=self.card_height_in_inches,
            )
        else:
            with open(image_path, "rb") as f:
                image_bytes = f.read()
            # Pass raw bytes so fpdf keys the cache by content hash rather than file path.
            # This ensures refreshed image files are re-read when re-exporting PDFs.
            self.pdf.image(image_bytes, x=0, y=0, w=self.card_width_in_inches, h=self.card_height_in_inches)

    def save_file(self) -> str:
        extra = ""
        if self.separate_faces:
            extra = f"{self.current_face}/"
        file_path = f"{self.save_path}{extra}{self.file_num}.pdf"
        self.pdf.output(file_path)
        self.saved_files.append(file_path)
        return file_path

    def download_and_collect_images(self, post_processing_config: Optional[ImagePostProcessingConfig]) -> None:
        download_config = None if self.export_mode == "drive_thru_cards" else post_processing_config
        with ThreadPoolExecutor(max_workers=THREADS) as pool:
            self.order.fronts.download_images(pool, self.download_bar, download_config)
            self.order.backs.download_images(pool, self.download_bar, download_config)

        failed_images = self.order.get_failed_downloads()
        if failed_images:
            raise ImageDownloadError(failed_images)

        backs_by_slots = {}
        for card in self.order.backs.cards_by_id.values():
            for slot in card.slots:
                backs_by_slots[slot] = card.file_path

        fronts_by_slots = {}
        for card in self.order.fronts.cards_by_id.values():
            for slot in card.slots:
                fronts_by_slots[slot] = card.file_path

        paths_by_slot = {}
        for slot in fronts_by_slots.keys():
            paths_by_slot[slot] = (str(backs_by_slots.get(slot, backs_by_slots[0])), str(fronts_by_slots[slot]))
        self.paths_by_slot = paths_by_slot

    def execute(self, post_processing_config: Optional[ImagePostProcessingConfig]) -> list[str]:
        if self.export_mode == "drive_thru_cards" and post_processing_config is not None:
            # Calculate exact pixel dimensions for the target DPI at DTC card size (2.73" x 3.71")
            post_processing_config.target_pixel_size = calculate_dtc_target_pixel_size(post_processing_config.max_dpi)
            # Embed DPI metadata so PDF tools correctly interpret the image resolution
            post_processing_config.embed_dpi_metadata = True
        self.image_post_processing_config = post_processing_config
        try:
            self.download_and_collect_images(post_processing_config=post_processing_config)
            try:
                if self.separate_faces:
                    self.number_of_cards_per_file = 1
                    self.export_separate_faces()
                else:
                    self.export()
            finally:
                for tmp_path in self.processed_image_paths.values():
                    if os.path.exists(tmp_path):
                        os.unlink(tmp_path)
                self.processed_image_paths.clear()

            if self.pdfx_config:
                source_pdf_paths = list(self.saved_files)
                total_files = len(source_pdf_paths)
                for index, file_path in enumerate(source_pdf_paths, start=1):
                    logger.info(f"Converting PDF to PDF/X-1a ({index}/{total_files}): {file_path}")
                    pdfx_path = f"{os.path.splitext(file_path)[0]}_pdfx.pdf"
                    if convert_pdf_to_pdfx(file_path, pdfx_path, self.pdfx_config):
                        self.saved_files.append(pdfx_path)
                        logger.info(f"PDF/X-1a conversion succeeded: {pdfx_path}")
                    else:
                        logger.info(f"PDF/X-1a conversion failed for {file_path}. Using original PDF.")

            logger.info(f"Finished exporting files! They should be accessible at {self.save_path}.")
            return self.saved_files
        finally:
            # The bars are transient UI - clear them and release the terminal rows so subsequent
            # output (log lines, error summaries, later progress bars) flows naturally below the
            # scrolled log output instead of around bars pinned to the bottom of the window.
            self.status_bar.close(clear=True)
            self.download_bar.close(clear=True)
            self.processed_bar.close(clear=True)
            self.manager.stop()

    def export(self) -> None:
        for slot in sorted(self.paths_by_slot.keys()):
            (back_path, front_path) = self.paths_by_slot[slot]
            self.set_state(f"Working on slot {slot}")
            if slot == 0:
                self.generate_pdf()
            elif slot % self.number_of_cards_per_file == 0:
                self.set_state(f"Saving PDF #{slot}")
                self.save_file()
                self.file_num = self.file_num + 1
                self.generate_pdf()
            self.set_state(f"Adding images for slot {slot}")
            self.add_image(back_path)
            self.add_image(front_path)
            self.processed_bar.update()

        self.set_state(f"Saving PDF #{self.file_num}")
        self.save_file()

    def export_separate_faces(self) -> None:
        all_faces = ["backs", "fronts"]
        for slot in sorted(self.paths_by_slot.keys()):
            image_paths_tuple = self.paths_by_slot[slot]
            self.set_state(f"Working on slot {slot}")
            for face in all_faces:
                face_index = all_faces.index(face)
                self.current_face = face
                self.generate_pdf()
                self.add_image(image_paths_tuple[face_index])
                self.set_state(f"Saving {face} PDF for slot {slot}")
                self.save_file()
                if face_index == 1:
                    self.file_num = self.file_num + 1
            self.processed_bar.update()
