# Generated by Django 3.1.3 on 2021-01-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="source",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
