# Generated by Django 3.0.5 on 2020-04-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpicker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='source',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
