# Generated by Django 3.0.5 on 2020-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardpicker', '0002_card_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
