# Generated by Django 3.0.8 on 2021-04-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardpicker', '0008_auto_20210405_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='avgdpi',
        ),
    ]
