# Generated by Django 3.2.3 on 2021-05-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardpicker', '0009_remove_source_avgdpi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterModelOptions(
            name='cardback',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['-priority']},
        ),
    ]
