# Generated by Django 3.2.3 on 2021-05-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0011_auto_20210518_2306"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="drive_link",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="source",
            name="drive_id",
            field=models.CharField(max_length=100, unique=False),
        ),
    ]
