# Generated by Django 3.2.3 on 2021-05-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0012_auto_20210518_2352"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="drive_link",
        ),
    ]
