# Generated by Django 3.2.3 on 2021-05-25 21:07

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0013_auto_20210525_2243"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="searchq_text",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cardback",
            name="searchq_text",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="token",
            name="searchq_text",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="searchq",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name="cardback",
            name="searchq",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="searchq",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
