# Generated by Django 3.2.4 on 2021-09-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardpicker', '0017_auto_20210815_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='reddit',
        ),
        migrations.RemoveField(
            model_name='source',
            name='username',
        ),
    ]
