# Generated by Django 4.0.5 on 2022-07-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0018_auto_20210922_1827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="drive_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
