# Generated by Django 4.0.6 on 2022-07-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0020_refactor_primary_key"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ["ordinal"]},
        ),
        migrations.RenameField(
            model_name="source",
            old_name="order",
            new_name="ordinal",
        ),
    ]
