# Generated by Django 4.0.6 on 2022-07-30 05:15

from django.db import migrations, models


def insert_source_name(apps, schema_editor) -> None:  # type: ignore  # TODO: type this properly
    model = apps.get_model("cardpicker", "Source")
    for source in model.objects.all():
        source.name = source.key
        source.save()


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0021_alter_source_options_rename_order_source_ordinal"),
    ]

    operations = [
        migrations.AddField(model_name="source", name="name", field=models.CharField(max_length=50, null=True)),
        migrations.RunPython(insert_source_name),
        migrations.AlterField(model_name="source", name="name", field=models.CharField(max_length=50, unique=True)),
    ]
