# Generated by Django 4.0.6 on 2022-08-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0022_source_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="source_type",
            field=models.CharField(
                choices=[("GOOGLE_DRIVE", "Google Drive"), ("LOCAL_FILE", "Local File"), ("AWS_S3", "AWS S3")],
                default="GOOGLE_DRIVE",
                max_length=20,
            ),
        ),
    ]
