# Generated by Django 4.0.6 on 2022-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cardpicker", "0023_source_source_type")]

    operations = [
        # expand `drive_id` fields to 200 characters
        migrations.AlterField(model_name="card", name="drive_id", field=models.CharField(max_length=200, unique=True)),
        migrations.AlterField(
            model_name="cardback", name="drive_id", field=models.CharField(max_length=200, unique=True)
        ),
        migrations.AlterField(
            model_name="source", name="drive_id", field=models.CharField(max_length=200, unique=True)
        ),
        migrations.AlterField(model_name="token", name="drive_id", field=models.CharField(max_length=200, unique=True)),
        # rename `drive_id` to `identifier`
        migrations.RenameField(model_name="card", old_name="drive_id", new_name="identifier"),
        migrations.RenameField(model_name="cardback", old_name="drive_id", new_name="identifier"),
        migrations.RenameField(model_name="token", old_name="drive_id", new_name="identifier"),
        migrations.RenameField(model_name="source", old_name="drive_id", new_name="identifier"),
        # rename `drive_link` to `external_link`
        migrations.RenameField(model_name="source", old_name="drive_link", new_name="external_link"),
    ]
