# Generated by Django 4.1.1 on 2022-10-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0025_card_folder_location_cardback_folder_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="source",
        ),
        migrations.AddField(
            model_name="card",
            name="card_type",
            field=models.CharField(
                choices=[("CARD", "Card"), ("CARDBACK", "Cardback"), ("TOKEN", "Token")], default="CARD", max_length=20
            ),
        ),
        migrations.DeleteModel(
            name="Cardback",
        ),
        migrations.DeleteModel(
            name="Token",
        ),
    ]
