# Generated by Django 4.1.2 on 2022-11-01 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0026_remove_token_source_card_card_type_delete_cardback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20), default=list, size=None
            ),
        ),
    ]
