# Generated by Django 4.1.1 on 2022-10-23 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import cardpicker.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cardpicker", "0026_remove_token_source_card_card_type_delete_cardback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("date_created", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_modified", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cardstock",
                    models.CharField(
                        choices=[
                            ("S30_FOIL", "S30 (Standard Smooth)"),
                            ("S30_NONFOIL", "S30 (Standard Smooth) — Foil"),
                            ("S33_FOIL", "S33 (Superior Smooth)"),
                            ("S33_NONFOIL", "S33 (Superior Smooth) — Foil"),
                            ("M31_FOIL", "M31 (Linen)"),
                            ("M31_NONFOIL", "M31 (Linen) — Foil"),
                            ("P10_NONFOIL", "P10 (Plastic)"),
                        ],
                        default="S30_FOIL",
                        max_length=20,
                    ),
                ),
                (
                    "cardback",
                    models.ForeignKey(
                        default=cardpicker.models.get_default_cardback,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cardpicker.card",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.CharField(max_length=200)),
                ("slot", models.IntegerField()),
                (
                    "face",
                    models.CharField(choices=[("FRONT", "Front"), ("BACK", "Back")], default="FRONT", max_length=5),
                ),
                (
                    "card",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cardpicker.card"
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cardpicker.project")),
            ],
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(fields=("card", "project", "slot", "face"), name="projectmember_unique"),
        ),
    ]
