# Generated by Django 4.1.1 on 2022-11-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0028_source_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="key",
            field=models.UUIDField(auto_created=True, unique=True),
        ),
    ]
