# Generated by Django 4.1.7 on 2023-05-01 06:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0029_alter_project_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="description",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
