# Generated by Django 4.2.3 on 2023-08-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0031_card_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmember",
            name="card",
        ),
        migrations.AddField(
            model_name="projectmember",
            name="card_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
