# Generated by Django 4.2.3 on 2023-08-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cardpicker", "0032_remove_projectmember_card_projectmember_card_id")]

    operations = [
        migrations.AddField(
            model_name="card",
            name="language",
            field=models.CharField(default="EN", max_length=5),
            preserve_default=False,
        ),
    ]
