# Generated by Django 4.2.3 on 2023-09-07 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("cardpicker", "0036_remove_dfcpair_back_searchable_and_more")]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cardpicker.tag"
            ),
        )
    ]
