# Generated by Django 4.2.18 on 2025-01-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0038_tag_is_enabled_by_default"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="searchq_keyword",
        ),
    ]
