# Generated by Django 4.2.14 on 2025-05-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0039_remove_card_searchq_keyword"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="date",
            new_name="date_created",
        ),
    ]
