# Generated by Django 4.2.14 on 2025-05-16 21:15

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0040_rename_date_card_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="date_modified",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.RunSQL(
            sql="UPDATE cardpicker_card SET date_modified = date_created", reverse_sql=migrations.RunSQL.noop
        ),
    ]
