# Generated by Django 4.2.14 on 2025-05-18 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0041_card_date_modified"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectmember",
            name="projectmember_unique",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="card_id",
        ),
        migrations.AddField(
            model_name="projectmember",
            name="card",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cardpicker.card"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(fields=("card", "project", "slot", "face"), name="projectmember_unique"),
        ),
    ]
