# Generated by Django 4.2.14 on 2025-05-29 06:33

from django.db import migrations


def create_schedules(apps, schema_editor):  # type: ignore  # TODO
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.create(
        name="update_database",
        func="django.core.management.call_command",
        args="'update_database'",
        schedule_type="D",
    )
    Schedule.objects.create(
        name="update_dfcs",
        func="django.core.management.call_command",
        args="'update_dfcs'",
        schedule_type="W",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0042_remove_projectmember_projectmember_unique_and_more"),
        ("django_q", "0018_task_success_index"),  # manually added migration dependency
    ]

    operations = [
        migrations.RunPython(create_schedules),
    ]
