# Generated by Django 4.2.27 on 2026-04-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0043_auto_20250529_0233"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalArtist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CanonicalExpansion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.UUIDField(unique=True)),
                ("code", models.CharField(unique=True)),
                ("name", models.CharField(unique=True)),
                ("game", models.CharField(choices=[("MTG", "MTG")], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CanonicalCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identifier", models.UUIDField(unique=True)),
                ("name", models.TextField(db_index=True)),
                ("collector_number", models.CharField(max_length=16)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "artist",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cardpicker.canonicalartist"),
                ),
                (
                    "expansion",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cardpicker.canonicalexpansion"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="canonical_card",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="cardpicker.canonicalcard"
            ),
        ),
        migrations.AddField(
            model_name="canonicalcard",
            name="canonical_id",
            field=models.UUIDField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="canonicalcard",
            constraint=models.UniqueConstraint(
                fields=("expansion", "collector_number"), name="canonicalcard_unique_expansion_collector_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="canonicalcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("canonical_id",),
                name="canonicalcard_unique_default_per_canonical_id",
            ),
        ),
    ]
