# Generated by Django 4.2.27 on 2026-04-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0044_canonicalartist_canonicalexpansion_canonicalcard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalcard",
            name="image_hash",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
