# Generated by Django 4.2.27 on 2026-04-20 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0045_canonicalcard_image_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="image_hash",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="card",
            name="inferred_canonical_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inferred_canonical_card",
                to="cardpicker.canonicalcard",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="canonical_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="canonical_card",
                to="cardpicker.canonicalcard",
            ),
        ),
    ]
