# Generated by Django 4.2.27 on 2026-04-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0046_card_image_hash_card_inferred_canonical_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalcard",
            name="medium_thumbnail_url",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="canonicalcard",
            name="small_thumbnail_url",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
