# Generated by Django 4.2.27 on 2026-04-26 11:40

from django.db import migrations


def create_schedules(apps, schema_editor):  # type: ignore  # TODO
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.create(
        name="import_canonical_card_data",
        func="django.core.management.call_command",
        args="'import_canonical_card_data'",
        schedule_type="W",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0047_canonicalcard_medium_thumbnail_url_and_more"),
    ]

    operations = [
        migrations.RunPython(create_schedules),
    ]
