# Generated by Django 4.2.27 on 2026-04-30 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0048_auto_20260426_2140"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="canonical_artist",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="cardpicker.canonicalartist"
            ),
        ),
    ]
