# Generated by Django 4.2.25 on 2026-05-15 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardpicker", "0049_card_canonical_artist"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("count", models.IntegerField(default=0)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_counts",
                        to="cardpicker.card",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="downloadcount",
            constraint=models.UniqueConstraint(fields=("date", "card"), name="unique_downloadcount_date_card"),
        ),
    ]
