import pycountry

DATE_FORMAT = "jS F, Y"
DEFAULT_LANGUAGE = pycountry.languages.get(alpha_2="EN")

NEW_CARDS_PAGE_SIZE = 12
NEW_CARDS_DAYS = 14
SEARCH_RESULTS_PAGE_SIZE = 300
CARDS_PAGE_SIZE = 1000

MAX_SIZE_MB = 30
NSFW = "NSFW"
