name: Backend tests
description: Test the MPC Autofill Django backend
inputs:
  google-drive-api-key:
    description: Your Google Drive API key, required for running the database crawler
    required: true
  moxfield-secret:
    description: Your Moxfield API secret, required for pulling data from Moxfield
    required: true
runs:
  using: composite
  steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install Python dependencies
      working-directory: MPCAutofill
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Write Google Drive API credentials to file
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "client_secrets.json"
        json: ${{ inputs.google-drive-api-key }}
        dir: "MPCAutofill/"
    - name: Run backend tests
      run: |
        cd MPCAutofill && pytest .
      shell: bash
      env:
        MOXFIELD_SECRET: ${{ inputs.moxfield-secret }}
