name: Image CDN tests
runs:
  using: composite
  steps:
    - name: Install npm
      uses: actions/setup-node@v4
      with:
        node-version: 22.15
    - name: Compile image CDN
      working-directory: image-cdn
      run: |
        npm ci
      shell: bash
    - name: Run Vitest tests
      working-directory: image-cdn
      run: |
        npm run test
      shell: bash
