transforms = {'Aberrant Researcher': 'Perfected Form',
              'Accursed Witch': 'Infectious Curse',
              'Afflicted Deserter': 'Werewolf Ransacker',
              'Archangel Avacyn': 'Avacyn, the Purifier',
              "Arguel's Blood Fast": 'Temple of Aclazotz',
              'Arlinn Kord': 'Arlinn, Embraced by the Moon',
              'Autumnal Gloom': 'Ancient of the Equinox',
              'Avacynian Missionaries': 'Lunarch Inquisitors',
              "Azor's Gateway": 'Sanctum of the Sun',
              'Bloodline Keeper': 'Lord of Lineage',
              'Breakneck Rider': 'Neck Breaker',
              'Chalice of Life': 'Chalice of Death',
              'Chandra, Fire of Kaladesh': 'Chandra, Roaring Flame',
              'Chosen of Markov': "Markov's Servant",
              'Civilized Scholar': 'Homicidal Brute',
              'Cloistered Youth': 'Unholy Fiend',
              'Conduit of Storms': 'Conduit of Emrakul',
              "Conqueror's Galleon": "Conqueror's Foothold",
              'Convicted Killer': 'Branded Howler',
              'Cryptolith Fragment': 'Aurora of Emrakul',
              'Curious Homunculus': 'Voracious Reader',
              'Daring Sleuth': 'Bearer of Overwhelming Truths',
              'Daybreak Ranger': 'Nightfall Predator',
              'Delver of Secrets': 'Insectile Aberration',
              'Docent of Perfection': 'Final Iteration',
              'Dowsing Dagger': 'Lost Vale',
              'Duskwatch Recruiter': 'Krallenhorde Howler',
              'Elbrus, the Binding Blade': 'Withengar Unbound',
              'Elusive Tormentor': 'Insidious Mist',
              'Extricator of Sin': 'Extricator of Flesh',
              'Garruk Relentless': 'Garruk, the Veil-Cursed',
              'Gatstaf Arsonists': 'Gatstaf Ravagers',
              'Gatstaf Shepherd': 'Gatstaf Howler',
              'Geier Reach Bandit': 'Vildin-Pack Alpha',
              'Golden Guardian': 'Gold-Forge Garrison',
              'Grizzled Angler': 'Grisly Anglerfish',
              'Grizzled Outcasts': 'Krallenhorde Wantons',
              'Growing Rites of Itlimoc': 'Itlimoc, Cradle of the Sun',
              "Hadana's Climb": 'Winged Temple of Orazca',
              'Hanweir Militia Captain': 'Westvale Cult Leader',
              'Hanweir Watchkeep': 'Bane of Hanweir',
              'Harvest Hand': 'Scrounged Scythe',
              'Heir of Falkenrath': 'Heir to the Night',
              'Hermit of the Natterknolls': 'Lone Wolf of the Natterknolls',
              'Hinterland Hermit': 'Hinterland Scourge',
              'Hinterland Logger': 'Timber Shredder',
              'Huntmaster of the Fells': 'Ravager of the Fells',
              'Instigator Gang': 'Wildblood Pack',
              "Jace, Vryn's Prodigy": 'Jace, Telepath Unbound',
              'Journey to Eternity': 'Atzal, Cave of Eternity',
              'Kessig Forgemaster': 'Flameheart Werewolf',
              'Kessig Prowler': 'Sinuous Predator',
              'Kindly Stranger': 'Demon-Possessed Witch',
              'Kruin Outlaw': 'Terror of Kruin Pass',
              'Kytheon, Hero of Akros': 'Gideon, Battle-Forged',
              'Lambholt Elder': 'Silverpelt Werewolf',
              'Lambholt Pacifist': 'Lambholt Butcher',
              "Legion's Landing": 'Adanto, the First Fort',
              'Liliana, Heretical Healer': 'Liliana, Defiant Necromancer',
              'Lone Rider': 'It That Rides as One',
              'Loyal Cathar': 'Unhallowed Cathar',
              "Ludevic's Test Subject": "Ludevic's Abomination",
              'Mayor of Avabruck': 'Howlpack Alpha',
              'Mondronen Shaman': "Tovolar's Magehunter",
              'Neglected Heirloom': 'Ashmouth Blade',
              'Nicol Bolas, the Ravager': 'Nicol Bolas, the Arisen',
              'Nissa, Vastwood Seer': 'Nissa, Sage Animist',
              'Path of Mettle': 'Metzali, Tower of Triumph',
              'Pious Evangel': 'Wayward Disciple',
              'Primal Amulet': 'Primal Wellspring',
              'Profane Procession': 'Tomb of the Dusk Rose',
              'Ravenous Demon': 'Archdemon of Greed',
              'Reckless Waif': 'Merciless Predator',
              'Sage of Ancient Lore': 'Werewolf of Ancient Hunger',
              'Scorned Villager': 'Moonscarred Werewolf',
              'Screeching Bat': 'Stalking Vampire',
              'Search for Azcanta': 'Azcanta, the Sunken Ruin',
              'Shrill Howler': 'Howling Chorus',
              'Skin Invasion': 'Skin Shedder',
              'Smoldering Werewolf': 'Erupting Dreadwolf',
              'Solitary Hunter': 'One of the Pack',
              'Soul Seizer': 'Ghastly Haunting',
              'Startled Awake': 'Persistent Nightmare',
              'Storm the Vault': 'Vault of Catlacan',
              'Tangleclaw Werewolf': 'Fibrous Entangler',
              'Thaumatic Compass': 'Spires of Orazca',
              'Thing in the Ice': 'Awoken Horror',
              'Thraben Gargoyle': 'Stonewing Antagonizer',
              'Thraben Sentry': 'Thraben Militia',
              'Tormented Pariah': 'Rampaging Werewolf',
              'Town Gossipmonger': 'Incited Rabble',
              'Treasure Map': 'Treasure Cove',
              'Ulrich of the Krallenhorde': 'Ulrich, Uncontested Alpha',
              'Ulvenwald Captive': 'Ulvenwald Abomination',
              'Ulvenwald Mystics': 'Ulvenwald Primordials',
              'Uninvited Geist': 'Unimpeded Trespasser',
              "Vance's Blasting Cannons": 'Spitfire Bastion',
              'Vildin-Pack Outcast': 'Dronepack Kindred',
              'Village Ironsmith': 'Ironfang',
              'Village Messenger': 'Moonrise Intruder',
              'Villagers of Estwald': 'Howlpack of Estwald',
              'Voldaren Pariah': 'Abolisher of Bloodlines',
              'Westvale Abbey': 'Ormendahl, Profane Prince',
              'Wolfbitten Captive': 'Krallenhorde Killer',
              'Gisela, the Broken Blade': 'Brisela, Voice of Nightmares (Top)',
              'Bruna, the Fading Light': 'Brisela, Voice of Nightmares (Bottom)',
              'Hanweir Battlements': 'Hanweir, the Writhing Township (Top)',
              'Hanweir Garrison': 'Hanweir, the Writhing Township (Bottom)',
              'Graf Rats': 'Chittering Host (Top)',
              'Midnight Scavengers': 'Chittering Host (Bottom)'}

transforms = dict((k.lower(), v.lower()) for k, v in transforms.items())
