name: Tests
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  test-backend:
    name: Backend tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: mpcautofill
          POSTGRES_PASSWORD: mpcautofill
          POSTGRES_DB: mpcautofill
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-backend
        with:
          google-drive-api-key: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          moxfield-secret: ${{ secrets.MOXFIELD_SECRET }}
  test-desktop-tool:
    name: Desktop tool tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest
    #          - os: ubuntu-latest # https://github.com/browser-actions/setup-edge/issues/516
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-desktop-tool
        with:
          google-drive-api-key: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          moxfield-secret: ${{ secrets.MOXFIELD_SECRET }}
  test-frontend:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-frontend
  test-pre-commit:
    name: Formatting and static type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-pre-commit
