name: Frontend tests
on:
  pull_request:
    paths:
      - "frontend/**"
  workflow_dispatch:
jobs:
  test:
    name: Frontend tests (${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-frontend
        with:
          shard_index: ${{ matrix.shardIndex }}
          shard_total: ${{ matrix.shardTotal }}
  merge-reports:
    name: Merge Playwright reports
    if: ${{ !cancelled() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.15
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Download blob reports
        uses: actions/download-artifact@v4
        with:
          path: frontend/all-blob-reports
          pattern: blob-report-*
          merge-multiple: true
      - name: Merge reports
        working-directory: frontend
        run: npx playwright merge-reports --reporter html ./all-blob-reports
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
