name: Frontend tests
on:
  pull_request:
    paths:
      - "frontend/**"
  workflow_dispatch:
jobs:
  test-backend:
    name: Frontend tests
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-frontend
