name: Web CI
on:
  push:
    branches: ["master"]
    paths:
      - "frontend/**"
      - "MPCAutofill/**"
  workflow_dispatch:
jobs:
  test-backend:
    name: Backend tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: mpcautofill
          POSTGRES_PASSWORD: mpcautofill
          POSTGRES_DB: mpcautofill
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-backend
        with:
          google-drive-api-key: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          moxfield-secret: ${{ secrets.MOXFIELD_SECRET }}
  test-frontend:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-frontend
  test-pre-commit:
    name: Formatting and static type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test-pre-commit
  build-frontend:
    name: Build frontend
    needs: [test-backend, test-frontend, test-pre-commit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-frontend
        with:
          ga-measurement-id: ${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
          image-bucket-url: ${{ secrets.IMAGE_CDN_BUCKET_DOMAIN }}
          image-worker-url: ${{ secrets.IMAGE_CDN_WORKER_DOMAIN }}
          google-drive-client-id: ${{ secrets.NEXT_PUBLIC_GOOGLE_DRIVE_CLIENT_ID }}
          google-drive-app-id: ${{ secrets.NEXT_PUBLIC_GOOGLE_DRIVE_APP_ID }}
  publish-frontend:
    name: Publish frontend
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish-frontend
        with:
          github-api-token: ${{ secrets.API_TOKEN_GITHUB }}
